## Help Text

**General Infomation:**
This page gets the data on the thermal time the seed needs to germinate <span style="color:red">(Remember the thermal times here must ahere to the same base temperature as is stated in the sowing page)</span>. The fraction of seeds per thermal time is how this is calculated.   
***

### Generate hypothetical Data:
The data is generated for main or idealised seedlots.    

#### Defaults:
The defaults allow you to choose a seed lot tested with the TGB in 2014 and if you want specify the temperature at which the data was gained (it may be best if defining a temperature to use the one closest to the field). This defaults to all the seedlots monitered at all the temperatures.    

#### Advanced:
There is a tick box at the top to overwrite the example data (this tick box will supersede uploaded data too).   
There are 3 sliders *Total proportion of seeds germ*, *Thermal Time range* and *Thermal Time for Max Germination*.    
*Total proportion of seeds germ* selects the maximum fraction of seeds that will germinate.     
*Thermal Time range* selects the minimum and maximum range over which the seeds will germinate (No seeds will start germination until the minimum and none will germinate after the maximum).     
*Thermal Time for Max Germination* This sets the thermal time at which most seeds will germinate (or over longer germinations probides a secondary increase in rate). [This will just be ignored if it is set outside of the range]      
***

### Import:
Importing custom data will not overwrite data generated by the **Advanced tab** - uncheck the advanced tab if necessary.    
* The file imported must be in .csv format.  
* It must have the same headers as the example stock file.  
* The file must also be at least 2 records long {2 records can be used to achieve no seeds germinating}. 
* tgball uses Degree days the default data uses a base temperature of 0C to calculate these, if importing data that does not use 0C make sure you change the sowing conditions page to have a appropriate base temperature.     
* The Order column must exist however the data in it is for your information and is not read.     
* The last Record must have 1 as the fraction of seeds and 99999 as the thermal time {if all seeds germinate the penultimate record can just have 1 as the fraction of seeds as well}.    
***

### Graph:    
There is a graph tab that allows a visualisation of the data, showing the fraction of seed that have germinated on the Y axis and the thermal time in the X axis.    

### Data Chart:
There Is a chart at the bottom that represents the data currently intended for the model.  This chart updates as it is iterated so new data imported or generated should display here.    

#### Data Explanation:
**Order** is information for the user on the point the seeds are at.  
**Frc** is the proportion of seeds germinated at each thermal time {Must end in a 1}.  
**tgball** is a selection of thermal times this defaults to 14 {the last one must be 99999}.


***

