## Help Text

**General Infomation:**  
This Page specifies the soil clod structure as with the other specifications data can be imported, defaults can be chosen from a list or idealised data can be generated.   
***

### Generate hypothetical Data:
There are *default* and *advanced* sets of default data the advanced gives more options.    

#### Defaults:
The defaults are **defaults** which has a normal range of clods, **No.clods** this has only tiny clods, **small clods** which has many 5mm clods, **Big clods** which has clods up to 200mm and Welsh which has an extensive range of clods.     

#### Advanced:
Tick use sliders to use the advanced settings options.     
The first slider *Clod Range* gives the minimun and maximum size of clod to simulate in the seed bed.  The second slider *No of smallest clods* allows a selection of the number of minimum sized clods as does the last slider with the largest clods (the other clod sizes and amounts are calculated on a linear scale with the set clods. Below this are radio buttons for the probability that the clods will be lying on the soil surface - this is settable to *None* or *All* or it can increase or decrease with size of the clods in question. 
***

### Import:
Importing custom data will not overwrite data generated by the advanced tab - uncheck the advanced tab if nessesery.  
* The file imported must be in .csv format.  
* It Must have the same headers as the example stock file.  
* The file must also be at least 2 and no more than 50 records long.
* All probabilities must be between 0 and 1.
* The Min.Size setting is the minimum size clods in this category will be between this size and the size above.
* ALL CLOD NUMBERS ARE PER METER SQUARE AND 4CM DEEP (if you enter these proportions it will calculate the amount for your plot)
* Clods are placed in reverse order to they are listed so normally the largest clods at the bottom of the table are placed first - not setting imported data out this way may make generating a seedbed more difficult.
***

#### Data:
**No.of.Clods** is the number of clods for each size found in a 4cm deep 1 square meter patch of earth.  
**Min.Size** all the clods will be generated between this size and the size above {this system comes from the practicalities of sieving soil}.  
**P.on.Surface** this is the probability the clod is visible on the surface.  
**P.Stuk.Surface** is the probability a clod on the surface is more than 50% out of the ground.
**P.Stuck.Surface** is the probability a clod on the surface is less than 30% visible.


***

